apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudops-config
  namespace: cloudops
data:
  APP_PORT: "8081"
  POSTGRES_DB: "cloudops"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://cloudops-postgres:5432/cloudops"
  SPRING_DATASOURCE_USERNAME: "cloudops"
