apiVersion: v1
kind: ConfigMap

metadata:
  name: cloudops-config
  namespace: cloudops

data:

  # PostgreSQL
  POSTGRES_DB: cloudops_db
  POSTGRES_USER: cloudops

  # Spring Boot
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/cloudops_db
  SPRING_DATASOURCE_USERNAME: cloudops

  #backen_port
  APP_PORT: "8081"
