apiVersion: v1
kind: Secret
metadata:
  name: cloudops-secret
  namespace: cloudops
type: Opaque
stringData:
  POSTGRES_USER: "cloudops"
  POSTGRES_PASSWORD: "cloudops123"
  SPRING_DATASOURCE_PASSWORD: "cloudops123"
