spring.application.name=cloudops-dashboard-backend

server.port=${APP_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloudops_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cloudops}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cloudops123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
